### ISSUE TITLE
Error upon join for all players

### ISSUE THREAD

**Issue by MStruntze** [TeamUlysses/ulib#1]
After updating to the latest version (retried as of today - same error), this error seems to occur when joining:
![Image of error](http://puu.sh/ln0Lj/d68fee5b86.png)

I don't know what information to provide you, so let me know.
Running DarkRP.

**Comment by SticklyMan** [comment]
This is a conflict between FPP and ULib- we're working on a solution at the moment.

**Comment by SticklyMan** [comment]
FPtje has just fixed this in the latest version of FPP.
https://github.com/FPtje/Falcos-Prop-protection/issues/147#issuecomment-157170477
