### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by deinemudda32** [TeamUlysses/ulib#10]
[ERROR] lua/includes/extensions/math.lua:46: attempt to compare nil with number
1. Clamp - lua/includes/extensions/math.lua:46
   1. ValueChanged - addons/ulx/lua/ulx/modules/cl/xgui_helpers.lua:261
   2. SetValue - addons/ulx/lua/ulx/modules/cl/xlib.lua:587
      1. unknown - addons/ulx/lua/ulx/modules/cl/xlib.lua

**Comment by Nayruden** [comment]
What were you doing when you received this error?

**Comment by deinemudda32** [comment]
Happend while browsing through the command categories randomly.

**Comment by ghost** [comment]
Is this fixed now got same issue

**Comment by Nayruden** [comment]
The issue shows as closed if it is fixed

**Comment by Nayruden** [comment]
@SticklyMan have you had a chance to look into this?

**Comment by SticklyMan** [comment]
I was only able to reproduce this after making a time-based NumArg restriction (ulx ban) with the same min and max that was not 0, then tried to set the time using the numberwang thing.

Not sure if that was the original issue, but the fix should work regardless. (Basically, there was invalid input sent to the code to enforce min/max constraints)
