### ISSUE TITLE
No way to prevent ULib.refreshBans call

### ISSUE THREAD

**Issue by MStruntze** [TeamUlysses/ulib#11]
If a larger part of the ban system has been replaced, and banid'ing all banned steamids is no longer wished, it's impossible to prevent it without modifying ULib.
I have my bans stored in a database and they are loaded from a database. I do not wish that all those bans are being banid'ed since there's no point in doing more than removing the from the ULib.bans upon unban.
Overwriting the refreshBans function isn't an option since it's called right after definition. Could there be some way to prevent [this function](https://github.com/TeamUlysses/ulib/blob/master/lua/ulib/server/player.lua#L403) from running?

**Comment by Nayruden** [comment]
Fair points. I'll change it to load on a hook instead, so you will be able
to remove it.
