### ISSUE TITLE
ban length on disconnect message show an hour as 59 minutes

### ISSUE THREAD

**Issue by fruitwasp** [TeamUlysses/ulib#14]
### Steps to reproduce
1. ban a player for an hour.
### Expected behavior

ban length on disconnect message should show 60 minutes or 1 hour.
### Actual behavior

ban length on disconnect message shows 59 minutes 
### Version

ULib v2.52d (01/09/16)
ULX v3.62d (01/01/16)
### Extra

Code causing it: https://github.com/TeamUlysses/ulib/blob/5652d868bab0848abaf682f75b92871033a26bbe/lua/ulib/shared/misc.lua#L830

The converted time is only used as a string on the disconnect message, therefore I don't see why.

**Comment by Nayruden** [comment]
Huh, that seems like something I probably had some reason for the way I implemented it, but I don't remember why.

**Comment by Nayruden** [comment]
Closed with 2bb1db40770b469983ec89956c46e7fb3ea1d1f2
