### ISSUE TITLE
Random NULL entity error

### ISSUE THREAD

**Issue by ZachPL** [TeamUlysses/ulib#15]
### Error(s) in server console, if any

L 03/30/2016 - 01:34:18: "Daedelus<162><STEAM_0:0:50157625><>" entered the game
L 03/30/2016 - 01:34:18: "Daedelus<162><STEAM_0:0:50157625><>" disconnected (reason "Disconnect by user.")
L 03/30/2016 - 01:34:18: Lua Error: 
[ERROR] addons/ulib/lua/ulib/shared/hook.lua:110: addons/ulib/lua/ulib/server/ucl.lua:653: Tried to use a NULL entity!
1. fn - [C]:-1
   1. unknown - addons/ulib/lua/ulib/shared/hook.lua:110
### Version

I'll grab the version when I get home, although I believe it's up to date, at least the ucl file is.

**Comment by Nayruden** [comment]
You should have more lines in the error than that -- can you post the full error?

**Comment by ZachPL** [comment]
L 03/30/2016 - 01:34:01: Round ended.
L 03/30/2016 - 01:34:01: Result: innocent win.
L 03/30/2016 - 01:34:18: "Daedelus<162><STEAM_0:0:50157625><>" entered the game
L 03/30/2016 - 01:34:18: "Daedelus<162><STEAM_0:0:50157625><>" disconnected (reason "Disconnect by user.")
L 03/30/2016 - 01:34:18: Lua Error: 
[ERROR] addons/ulib/lua/ulib/shared/hook.lua:110: addons/ulib/lua/ulib/server/ucl.lua:653: Tried to use a NULL entity!
1. fn - [C]:-1
   1. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

L 03/30/2016 - 01:34:36: Round proper has begun...
L 03/30/2016 - 01:34:36: 00:00.60 - DMG:     Sans [innocent] damaged captain cunch+bleach [traitor] for 148 dmg
L 03/30/2016 - 01:34:36: 00:00.60 - KILL:    Sans [innocent] killed captain cunch+bleach [traitor]
L 03/30/2016 - 01:34:37: Round ended.
L 03/30/2016 - 01:34:37: Result: innocent win.
L 03/30/2016 - 01:34:52: Log file closed.

That's the only error that is in the log, map didn't last long as it was early and not a lot of players were on.

**Comment by ZachPL** [comment]
I just noticed a similar error

L 04/03/2016 - 23:59:18: "gmo<1471><STEAM_0:0:91092683><>" connected, address "23.243.101.215:27005"
L 04/03/2016 - 23:59:19: "gmo<1471><STEAM_0:0:91092683><>" STEAM USERID validated
L 04/03/2016 - 23:59:21: "oneshotonPCin420p<1469><STEAM_0:0:103072541><>" disconnected (reason "Disconnect by user.")
L 04/03/2016 - 23:59:23: "gmo<1471><STEAM_0:0:91092683><>" entered the game
L 04/03/2016 - 23:59:23: "gmo<1471><STEAM_0:0:91092683><>" disconnected (reason "Disconnect by user.")
L 04/03/2016 - 23:59:23: Lua Error: 
[ERROR] addons/ulib/lua/ulib/shared/hook.lua:110: addons/anotherulxsbanmodule/lua/ulx/modules/sban.lua:380: Tried to use a NULL entity!
1. fn - [C]:-1
   1. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

So this might have to do with my sourcebans plugin and not necessarily ulib

**Comment by Nayruden** [comment]
Without a full stack trace, it's difficult to know the exact cause. I took my best guess as to where the error was occurring. It does seem sourcebans related, but it's ultimately something that ULX should be handling as well.
