### ISSUE TITLE
lua error when editing a ban

### ISSUE THREAD

**Issue by ghost** [TeamUlysses/ulib#17]
### Steps to reproduce

1.ban someone
2.go to ban in GUI 
3.then edit the ban 
### Expected behavior

Tell us what should happen
Should change the ban without making luas
### Actual behavior

Tell us what happens instead
Made luas
### Error(s) in server console, if any

[ERROR] addons/ulib/lua/ulib/server/player.lua:167: attempt to call method 'Kick' (a nil value)
1. kick - addons/ulib/lua/ulib/server/player.lua:167
2. banfunc - addons/ulib/lua/ulib/server/player.lua:275
3. addBan - addons/ulx/lua/ulx/xgui/server/sv_bans.lua:244
4. unknown - addons/ulx/lua/ulx/xgui/server/sv_bans.lua:84
5. unknown - addons/ulx/lua/ulx/modules/xgui_server.lua:65
6. unknown - lua/includes/modules/concommand.lua:54
### Error(s) in player's console, if any

Nope
### Version

Run "ulx version" in console and paste the result
I will get you that asap (on phone)

**Comment by Nayruden** [comment]
#18 -- user fixed, conflict with other addons.

**Comment by ghost** [comment]
this is still a error

**Comment by ghost** [comment]
can we reopen plz

**Comment by 60percentCaffeine** [comment]
@Gamerpro2266 
"made luas"
lol'd

Please, use "Lua-errors" instead of "luas".

**Comment by Nayruden** [comment]
The error you are getting indicates that your server is completely messed up. Recommend fresh reinstall and install addons carefully, one by one, to ensure you don't install one that destroys the Lua environment.

**Comment by ghost** [comment]
Is there no other way

**Comment by ghost** [comment]
Can I just reinstall the lua part

**Comment by 60percentCaffeine** [comment]
@Gamerpro2266 Yes, you can just do "app_update 4020 validate", copy your addons folder somewhere else and make a new folder, and then install addons one by one to find who is a bad boy.
