### ISSUE TITLE
Lua error when banning

### ISSUE THREAD

**Issue by ghost** [TeamUlysses/ulib#18]
### Steps to reproduce

1.ban someone for a week 
2.
3.
### Expected behavior

Tell us what should happen
Should ban with no luas made 
### Actual behavior

Tell us what happens instead
Made lua in console and doesnt show in gui bans
### Error(s) in server console, if any

ULib queue error: addons/ulib/lua/ulib/server/player.lua:167: attempt to call method 'Kick' (a nil value)
### Version

Run "ulx version" in console and paste the result
Get it asap (on phone)

**Comment by Nayruden** [comment]
Please run "ulx debuginfo" in server console and paste the results here.

**Comment by ghost** [comment]
] ulx version
ULib v2.61d (06/12/16)
ULX v3.71d (07/02/16)

**Comment by ghost** [comment]
[debugdump.txt](https://github.com/TeamUlysses/ulib/files/348019/debugdump.txt)

**Comment by Nayruden** [comment]
I'm fairly certain one of your many addons is doing something very bad to
your server. Please stop creating new issues until we resolve this one.
Please remove ALL other addons EXCEPT ulx/ulib and see if the problem
persists. If it does not, you will know one of your other addons is
seriously damaging the Lua environment.

**Comment by ghost** [comment]
Oh ok

**Comment by ghost** [comment]
Do you have any idea of what addon it might be

**Comment by ghost** [comment]
Could I add you on steam please
Mine is [OX:RP] Gamerpro2266

**Comment by Nayruden** [comment]
I do not have any idea what addon it is, and I am only rarely available for chats on Steam. Did you try disabling all addons yet?

**Comment by ghost** [comment]
No will do it later

**Comment by ghost** [comment]
all fixed it was some think called utime.lua was missing from a file

**Comment by ghost** [comment]
could i add you on steam please

**Comment by Nayruden** [comment]
Feel free -- http://steamcommunity.com/id/megiddo
