### ISSUE TITLE
Workshop Version: umsg error

### ISSUE THREAD

**Issue by robotboy655** [TeamUlysses/ulib#21]
```
Warning: Usermessage was larger than 256 bytes. This will cause problems.
Error sending usermessage - too large (ulib_repChangeC)Warning: Unhandled usermessage ''
```

I am assuming it is about ulib_repChangeCvar:
https://github.com/TeamUlysses/ulib/blob/81044e2a65790d264a45e9bbc54cbe1cb615b64c/lua/ulib/server/util.lua#L240-L245

Why does ULib still use user messages is beyond me.

This error happens with only ulib and ulx enabled.

**Comment by Nayruden** [comment]
Please share your configuration file

**Comment by robotboy655** [comment]
I did not change any configuration(s). Everything is on its default settings, all I did was subscribe to the mods on the Steam Workshop - ULX and ULib. If you insist, tell where do I find it.

**Comment by Nayruden** [comment]
Huh, the error is saying one of the ULX/ULib cvars is over 255 bytes, which is a known issue, but there's not really any good reason for such a large cvar value size (and definitely not any of the defaults). I can't look up the exact path right now, but I think the file is at data/ulx/config.txt.

**Comment by robotboy655** [comment]
http://pastebin.com/raw/KEnCzDGB

Here are the settings.
The issue is not that a convar is too large, it is that the usermessage contains > 255bytes of data.
You write like 3 strings into the usermessage.

Switch to net messages. You should've done this for everything years ago.

**Comment by JoshPiper** [comment]
This was fixed by @zpetty33 in https://github.com/TeamUlysses/ulib/commit/09c4e751a1deaec6202c7c5c23a8b11205720956.
