### ISSUE TITLE
Unauthed player

### ISSUE THREAD

**Issue by NullEnt1ty** [TeamUlysses/ulib#24]
### Steps to reproduce
1. Load a multiplayer game (I used a dedicated server)
2. Spawn several bots
### Expected behavior

Nothing unusual.
### Actual behavior

I got a clientside error from ULX. Seems to pop up randomly sometimes when a player joins.

Reverting commit https://github.com/TeamUlysses/ulib/commit/180d7370ef57147ba443c6f6b882c79eea512f71 seems to fix the issue (I spawned 30 bots and everything is running smoothly).
### Error(s) in server console, if any

-nothing, just clientside errors-
### Error(s) in player's console, if any

```
[ERROR] Unauthed player
  1. query - [C]:-1
   2. fn - addons/ulx/lua/ulx/xgui/bans.lua:519
    3. fn - addons/ulib/lua/ulib/shared/hook.lua:109
     4. func - addons/ulib/lua/ulib/client/cl_util.lua:22
      5. unknown - lua/includes/extensions/net.lua:32
```
### Version

ULib v2.61d (08/27/16)
ULX v3.71d (07/02/16)

**Comment by ghost** [comment]
I too am having this issue, what exactly would I need to do to revert the 'commit' you spoke of?  I am using my hosting providers SVN for ULX and ULIB.  This kicks out all sorts of funny errors for us and it seems to randomly select players to plague with the funny GUI errors which can also include being unable to open ULX menu and being unable to open the Q menu, rendering you unable to play the game.

**Comment by DipDipPotatoChip** [comment]
Owner of server with LordHolywell. I have reverted to commit 180d737. Everything seems to be in order, although this conclusion is being drawn after 5 minutes of stable gameplay. I will post back in this discussion if any more issues seem to arise. Thank you.

**Comment by ghost** [comment]
Been dealing with this same issue for 3 days. Completely wiped my server thinking it was a conflicting addon. I just ended up going back to ULib 2.61 and ULX 3.71 and everything works fine again.

Almost always occurs as someone is authed once joining and completely breaks xgui once the errors start.

**Comment by Nayruden** [comment]
The commit was reverted some time ago, sorry for the trouble, and thank you for reporting this. Keep in mind that if you are using the Git version, you are using a development version and these types of bugs slip by us occasionally here.
