### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by theaoneone** [TeamUlysses/ulib#28]
### Steps to reproduce

1.
2.
3.
### Expected behavior

Conflict with fin 2
### Actual behavior

No idea don't cause problems it seems
### Error(s) in server console, if any

Didn't find any
### Error(s) in player's console, if any

[ERROR] lua/includes/extensions/math.lua:54: attempt to perform arithmetic on local 'high' (a nil value)
1. Rand - lua/includes/extensions/math.lua:54
   1. fn - lua/autorun/server/sv_fin.lua:25
   2. unknown - lua/ulib/shared/hook.lua:110
### Version

Run "ulx version" in console and paste the result
I just updated it.

**Comment by Nayruden** [comment]
The error is inside a hook in sv_fin; ULib shows up in the stack trace due to how it modifies the hook library, but you'd get the error regardless of ULib's presence. Closing issue.
