### ISSUE TITLE
Overridden commands do not respect hide_say

### ISSUE THREAD

**Issue by Timmy** [TeamUlysses/ulib#31]
### Steps to reproduce
1. Use `ULib.HOOK_COMMAND_CALLED` to override a command that has `hide_say` set to true (e.g.: ulx psay).
```lua
-- lua/ulib/modules/server/psayoverride.lua
local function pSayOverride( ply, cmd )
  if cmd == "ulx psay" then
    return false -- Disallow
  end
end
hook.Add( ULib.HOOK_COMMAND_CALLED, "pSayOverride", pSayOverride )
```
2. Use the chat command to call the command.

### Expected behavior
The chat message should be suppressed.

### Actual behavior
The chat message appears in the chat box.

### Version
ULib v2.63d (03/21/17)
ULX v3.73d (03/21/17)

**Comment by iViscosity** [comment]
I think if [this line](https://github.com/TeamUlysses/ulib/blob/3e3e5fed7fbdaa7884f35330e0f1628948c4ddc8/lua/ulib/server/concommand.lua#L54) was changed to `return ""` rather than `return nil`, this would work.

Also, have you only tested with this command or other commands, as well?
