### ISSUE TITLE
ULib.execFile problems

### ISSUE THREAD

**Issue by zffs** [TeamUlysses/ulib#32]
Steps to reproduce

Create for example a server.cfg
Execute it with (in this case) "ulx exec server.cfg" (This command is using ULib.execFile)
Have fun.
Expected behavior

A config should get executed.

Actual behavior

The log got spammed.

Error(s) in server console, if any

http://hastebin.com/taqozogeyi.txt (it can also happen if there are other commands)

Version

ULib v2.61
ULX v3.71d (07/02/16)

With this I generated a 2 Gigabyte log on a test server.

**Comment by Nayruden** [comment]
Why did you close the issue?
