### ISSUE TITLE
HTTP failed - ISteamHTTP isn't available!

### ISSUE THREAD

**Issue by feavr** [TeamUlysses/ulib#34]
### Steps to reproduce
1. Have the ulib addon installed on a server.
2. Start the server normally.

### Expected behavior
No errors should be in the server console.

### Actual behavior
I haven't noticed anything out of the ordinary. However, it is a nuisance when trying to debug other addons.

### Error(s) in server console, if any
HTTP failed - ISteamHTTP isn't available!

### Version
v3.73d

**Comment by Nayruden** [comment]
Nuisance error, it is a known issue with the way the HTTP library works. Does not cause any degradation.
