### ISSUE TITLE
Lag with large number of bans (6k+)

### ISSUE THREAD

**Issue by Nayruden** [TeamUlysses/ulib#37]
Way ahead: 
1. Divorce ourselves of the Source Engine's ban mechanism altogether, as we can do it entirely in-house now with the "CheckPassword" hook.
2. Move data to SQLite.

**Comment by Codingale** [comment]
`users.txt` is also causing issues, if there are a large number of people to manage.

**Comment by Nayruden** [comment]
We've heard reports of that, but never actually observed it occurring in
the wild -- see referenced issue above. Folks who reported it were getting
lag from something else. If you believe you have that issue, please report
as such on the issue and we'll help troubleshoot on your server.

**Comment by Codingale** [comment]
We had to clear our `users.txt` we had over 8,000 users in a file as we restrict basic things behind a rank you simply ask for.

**Comment by Codingale** [comment]
Are you starting work on this or would it be acceptable if one of my friends starts work and makes a PR? He'd rather let you since you know what you're doing but he's always up for a challenge it seems..

**Comment by Nayruden** [comment]
Sorry @Codingale, forgot to reply earlier. I was mostly done when you posted your question, but now I've got an initial solution ready. Tentatively closing via 0b4cdd0acbf86597446dee4576e7ece9aea15999.

**Comment by Nayruden** [comment]
@Codingale mind testing it for me? Please report feedback at https://forums.ulyssesmod.net/index.php/topic,10520.0.html (trying to reach a wider audience than GitHub).

**Comment by Codingale** [comment]
Seems good so far, will keep you updated here and on the forums so far no issues, are there plans for `users.txt` too? That also causes lag with large files.

**Comment by Nayruden** [comment]
@Codingale I addressed that above, please see https://github.com/TeamUlysses/ulib/issues/37#issuecomment-327457445

**Comment by Codingale** [comment]
Alright so just send you a `users.txt`? It's the same issue once you have so many people...

**Comment by Nayruden** [comment]
Please take this discussion to the appropriate issue. Thanks!
