### ISSUE TITLE
serverside console flood

### ISSUE THREAD

**Issue by Karlend** [TeamUlysses/ulib#42]
1. We need to type "_u text" in console as client
2. We have "Unknown command: text" in server console

**Comment by Nayruden** [comment]
Why do you need to run "_u text"?

**Comment by Karlend** [comment]
everyone can run "_u text"...

**Comment by Nayruden** [comment]
And you have users running this repeatedly?

**Comment by Karlend** [comment]
Yes. Like for i=1,100 do RunConsoleCommand("_u", "hacked") end

**Comment by Nayruden** [comment]
It's annoying, but not really a problem. I'll see about adding what user it's coming from.

**Comment by SticklyMan** [comment]
This has been resolved in 58659ac275caffbaa689d5e835e7079f1128e1be
