### ISSUE TITLE
ULib.getUsers needs SteamName() check

### ISSUE THREAD

**Issue by Karlend** [TeamUlysses/ulib#44]
### Steps to reproduce
1. We can try to do something with player`s steam name

### Expected behavior
Find him

### Actual behavior
No target found or target has immunity!

### Version
ULib v2.63d
ULX v3.73d

## How to add
lua/ulib/shared/player.lua
245 string
if player:Nick():lower():find( piece:lower(), 1, true ) or player:SteamName():lower():find( piece:lower(), 1, true ) then

**Comment by Nayruden** [comment]
What condition leads to the steam name being different from the in-game
name?

**Comment by Karlend** [comment]
Darkrp rpname

**Comment by Nayruden** [comment]
In that case, why would you want to target by steam name rather than
in-game name?

**Comment by Karlend** [comment]
If you see profile/msg in steam group/private msg in steam. It will be much easier. Also notify about connection includes steam name

**Comment by Nayruden** [comment]
Sorry, but this would appeal to a very narrow band of users and confuse many others. For consistency and ease of use, we'll stick with in-game names.
