### ISSUE TITLE
Possible race condition between two users unbanning a player

### ISSUE THREAD

**Issue by deinemudda32** [TeamUlysses/ulib#5]
[ERROR] addons/ulx/lua/ulx/xgui/bans.lua:21: Tried to use invalid object (type Panel) (Object was NULL or not of the right type)
1. GetValue - [C]:-1
   1. DoClick - addons/ulx/lua/ulx/xgui/bans.lua:21
   2. OnMouseReleased - lua/vgui/dlabel.lua:218
      1. unknown - lua/vgui/dmenuoption.lua:116

I tried unbanning a nil user.

**Comment by Nayruden** [comment]
What do you mean by "a nil user"?

**Comment by deinemudda32** [comment]
I unbanned him with the xgui, but another admin unbanned him before, so I got this error after he was removed out of the banlist.

**Comment by Nayruden** [comment]
Hmm, I believe XGUI is supposed to remove the user from your list, but it's definitely a timing issue XGUI should check for regardless.

**Comment by SticklyMan** [comment]
Fixed in https://github.com/TeamUlysses/ulx/commit/4b5d7291e3ffa129c1f73918371f142c54deba2e
