### ISSUE TITLE
How to fix this

### ISSUE THREAD

**Issue by Haxo24** [TeamUlysses/ulib#51]
I would like to know how to fix this

### Error(s) in server console, if any
n - [C]:-1

Error in hook PostDrawViewModel: lua/tfa/modules/tfa_vm_blur.lua:145: attempt to call method 'DrawLaser' (a nil value)
stack traceback:
	lua/tfa/modules/tfa_vm_blur.lua:145: in function 'fn'
	addons/ulib-master/lua/ulib/shared/hook.lua:109: in function <addons/ulib-master/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

Error in hook PostDrawViewModel: lua/tfa/modules/tfa_vm_blur.lua:145: attempt to call method 'DrawLaser' (a nil value)
stack traceback:
	lua/tfa/modules/tfa_vm_blur.lua:145: in function 'fn'
	addons/ulib-master/lua/ulib/shared/hook.lua:109: in function <addons/ulib-master/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

Error in hook PostDrawViewModel: lua/tfa/modules/tfa_vm_blur.lua:145: attempt to call method 'DrawLaser' (a nil value)
stack traceback:
	lua/tfa/modules/tfa_vm_blur.lua:145: in function 'fn'
	addons/ulib-master/lua/ulib/shared/hook.lua:109: in function <addons/ulib-master/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

Error in hook PostDrawViewModel: lua/tfa/modules/tfa_vm_blur.lua:145: attempt to call method 'DrawLaser' (a nil value)
stack traceback:
	lua/tfa/modules/tfa_vm_blur.lua:145: in function 'fn'
	addons/ulib-master/lua/ulib/shared/hook.lua:109: in function <addons/ulib-master/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

Error in hook PostDrawViewModel: lua/tfa/modules/tfa_vm_blur.lua:145: attempt to call method 'DrawLaser' (a nil value)
stack traceback:
	lua/tfa/modules/tfa_vm_blur.lua:145: in function 'fn'
	addons/ulib-master/lua/ulib/shared/hook.lua:109: in function <addons/ulib-master/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

Error in hook PostDrawViewModel: lua/tfa/modules/tfa_vm_blur.lua:145: attempt to call method 'DrawLaser' (a nil value)
stack traceback:
	lua/tfa/modules/tfa_vm_blur.lua:145: in function 'fn'
	addons/ulib-master/lua/ulib/shared/hook.lua:109: in function <addons/ulib-master/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

Error in hook PostDrawViewModel: lua/tfa/modules/tfa_vm_blur.lua:145: attempt to call method 'DrawLaser' (a nil value)
stack traceback:
	lua/tfa/modules/tfa_vm_blur.lua:145: in function 'fn'
	addons/ulib-master/lua/ulib/shared/hook.lua:109: in function <addons/ulib-master/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

Error in hook PostDrawViewModel: lua/tfa/modules/tfa_vm_blur.lua:145: attempt to call method 'DrawLaser' (a nil value)
stack traceback:
	lua/tfa/modules/tfa_vm_blur.lua:145: in function 'fn'
	addons/ulib-master/lua/ulib/shared/hook.lua:109: in function <addons/ulib-master/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

Error in hook PostDrawViewModel: lua/tfa/modules/tfa_vm_blur.lua:145: attempt to call method 'DrawLaser' (a nil value)
stack traceback:
	lua/tfa/modules/tfa_vm_blur.lua:145: in function 'fn'
	addons/ulib-master/lua/ulib/shared/hook.lua:109: in function <addons/ulib-master/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

Error in hook PostDrawViewModel: lua/tfa/modules/tfa_vm_blur.lua:145: attempt to call method 'DrawLaser' (a nil value)
stack traceback:
	lua/tfa/modules/tfa_vm_blur.lua:145: in function 'fn'
	addons/ulib-master/lua/ulib/shared/hook.lua:109: in function <addons/ulib-master/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

Error in hook PostDrawViewModel: lua/tfa/modules/tfa_vm_blur.lua:145: attempt to call method 'DrawLaser' (a nil value)
stack traceback:
	lua/tfa/modules/tfa_vm_blur.lua:145: in function 'fn'
	addons/ulib-master/lua/ulib/shared/hook.lua:109: in function <addons/ulib-master/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

Error in hook PostDrawViewModel: lua/tfa/modules/tfa_vm_blur.lua:145: attempt to call method 'DrawLaser' (a nil value)
stack traceback:
	lua/tfa/modules/tfa_vm_blur.lua:145: in function 'fn'
	addons/ulib-master/lua/ulib/shared/hook.lua:109: in function <addons/ulib-master/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

Error in hook PostDrawViewModel: lua/tfa/modules/tfa_vm_blur.lua:145: attempt to call method 'DrawLaser' (a nil value)
stack traceback:
	lua/tfa/modules/tfa_vm_blur.lua:145: in function 'fn'
	addons/ulib-master/lua/ulib/shared/hook.lua:109: in function <addons/ulib-master/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

Error in hook PostDrawViewModel: lua/tfa/modules/tfa_vm_blur.lua:145: attempt to call method 'DrawLaser' (a nil value)
stack traceback:
	lua/tfa/modules/tfa_vm_blur.lua:145: in function 'fn'
	addons/ulib-master/lua/ulib/shared/hook.lua:109: in function <addons/ulib-master/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

Error in hook PostDrawViewModel: lua/tfa/modules/tfa_vm_blur.lua:145: attempt to call method 'DrawLaser' (a nil value)
stack traceback:
	lua/tfa/modules/tfa_vm_blur.lua:145: in function 'fn'
	addons/ulib-master/lua/ulib/shared/hook.lua:109: in function <addons/ulib-master/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

Error in hook PostDrawViewModel: lua/tfa/modules/tfa_vm_blur.lua:145: attempt to call method 'DrawLaser' (a nil value)
stack traceback:
	lua/tfa/modules/tfa_vm_blur.lua:145: in function 'fn'
	addons/ulib-master/lua/ulib/shared/hook.lua:109: in function <addons/ulib-master/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

Error in hook PostDrawViewModel: lua/tfa/modules/tfa_vm_blur.lua:145: attempt to call

**Comment by CattoGamer** [comment]
Not a ulib issue, contact TFA for fix his mess.
