### ISSUE TITLE
Nutscript 1.1 Extreame Lagg

### ISSUE THREAD

**Issue by ThomasTwoFace** [TeamUlysses/ulib#54]
### Steps to reproduce
1.Run the server as normal
2.Wait for the serve to populate
3. Extream lagg that affects everyone to the point that people cant move

### Expected behavior
Extreme lagg to the point that people cant move or drive

### Actual behavior
Please find the enclosed screenshot

### Version
Run "ulx version" in console and paste the result
![nutscript](https://user-images.githubusercontent.com/47926853/53290552-96bef180-379d-11e9-9fea-213543f0ce19.PNG)

**Comment by djtb2924** [comment]
What relationship with ulib ?

**Comment by Nayruden** [comment]
Not sure why OP is getting this message, but Google pulls up nothing about any ULX/Nutscript conflicts and ULX is actually recommended by the developers -- https://nutscript.miraheze.org/wiki/Installing_Nutscript .
