### ISSUE TITLE
IsWorldClicker error

### ISSUE THREAD

**Issue by NovaAstral** [TeamUlysses/ulib#56]
### Steps to reproduce
1. Join friends p2p server
2. Hold C to try using the context menu (GB radial does a similar error too when trying to open its options menu with right click while its open)
3. profit??

### Expected behavior
Tell us what should happen
Context menu should open (GB Radial settings should open)

### Actual behavior
Tell us what happens instead
Error Happens the entire time the context menu when hovering over anything in the world, right clicking on anything does not work (With GB Radial, the settings menu does not open)

### Error(s) in server console, if any
No errors in friends console

### Error(s) in player's console, if any
[ULib] lua/includes/modules/properties.lua:214: attempt to call method 'IsWorldClicker' (a nil value)
  1. fn - lua/includes/modules/properties.lua:214
   2. unknown - lua/ulib/shared/hook.lua:109

##GB Radial Error
[ULib] lua/includes/modules/properties.lua:199: attempt to call method 'IsWorldClicker' (a nil value)
  1. fn - lua/includes/modules/properties.lua:199
   2. unknown - lua/ulib/shared/hook.lua:109

### Version
ULib v2.63w
ULX v3.73w

**Comment by Nayruden** [comment]
ULib changes the way the hooking system works, which is why you see it in the stack trace. However, the bug lies in the addon (GB radial), not ULib or ULX.

**Comment by NovaAstral** [comment]
This happens without Gb radial, I included that error just incase, I think we can test what addon would be causing it though (Probably should've done thst in the first place)
