### ISSUE TITLE
ulx removeuser in console doesn't call ULibUserRemoved or ULibUserGroupChange hooks

### ISSUE THREAD

**Issue by LivacoNew** [TeamUlysses/ulib#60]
### Steps to reproduce
1. Make a user something other than user.
2. Make a hook for either ULibUserRemoved and ULibUserGroupChange and make it just print something.
2. Run ulx removeuser on that user in the console.
3. Hook shows nothing.

### Expected behavior
The hook runs after the command is called in the console, just like removing the user in the UI.

### Actual behavior
Neither hook is called when command is ran from console, while removing them from the UI is just fine.

### Error(s) in server console, if any
N/A

### Error(s) in player's console, if any
N/A

### Version
Run "ulx version" in console and paste the result
ULib v2.63
ULX v3.73

### Some extra media because i'm nice:
https://upload.livaco.dev/u/7NGbJqYT6V.png
https://upload.livaco.dev/u/EkeXgjKBdW.png (nothing being printed)
https://upload.livaco.dev/u/8YLDoSfIjO.png (b is printed because the hook is called - this is me removing myself from the GUI)

**Comment by zpetty33** [comment]
![image](https://user-images.githubusercontent.com/1337776/183222345-da1557b0-b8bf-4818-a112-2042b5b42702.png)

I'm afraid I'm unable to reproduce this issue. The hook seems to call just fine for me on the latest version ULib.
