### ISSUE TITLE
[ULib] RunConsoleCommand: Command is blocked! (exec)

### ISSUE THREAD

**Issue by RalphORama** [TeamUlysses/ulib#61]
### Steps to reproduce
1. Create a cfg file in `garrysmod/cfg` (i.e. `ttt.cfg`)
2. In a Lua script, run the code `RunConsoleCommand("exec", "ttt.cfg")`
3. Error appears in console (see "Error(s) in server console" section)

### Expected behavior

The console command `exec ttt.cfg` should execute without Ulib interference

### Actual behavior

Execution is blocked

### Error(s) in server console, if any

```
[ULib] RunConsoleCommand: Command is blocked! (exec)

  1. fn - addons/ttt_playercount_settings/lua/autorun/server/choose_config.lua:4
   2. unknown - lua/ulib/shared/hook.lua:109
```

### Error(s) in player's console, if any

n/a

### Version

```
ULib v2.63w
ULX v3.73w
```

**Comment by Nayruden** [comment]
This is a limitation in gmod and why we created a command to execute
configs.

**Comment by RalphORama** [comment]
> This is a limitation in gmod and why we created a command to execute configs.

What is the command / Lua call?  I'm paging through the Ulib documentation but don't see it.

**Comment by Nayruden** [comment]
http://ulyssesmod.net/docs/files/lua/ulib/shared/util-lua.html#execFile
