### ISSUE TITLE
Memory leak BackwardsHooks not cleared when entity key'd hook removed

### ISSUE THREAD

**Issue by thegrb93** [TeamUlysses/ulib#67]
https://github.com/TeamUlysses/ulib/blob/e887b4086124a69fad9efd58ce6ce4311d60e3aa/lua/ulib/shared/hook.lua#L132
Leads to a memory leak.

**Comment by thegrb93** [comment]
Add `BackwardsHooks[ name ][ k ] = nil` to fix

**Comment by zpetty33** [comment]
Added. Thank you for finding this!
