### ISSUE TITLE
ULib queue error: lua/includes/util/color.lua:16: bad argument #1 to 'min' (number expected, got nil)

### ISSUE THREAD

**Issue by marcquebec** [TeamUlysses/ulib#68]
### Steps to reproduce
1. Install ULib v2.63 + ULX v3.73 on dedicated gmod TTT server
2. ???
3. Join server and error popups once it's done loading 

### Expected behavior
Tell us what should happen
No errors
### Actual behavior
Tell us what happens instead
Error
### Error(s) in server console, if any
[ulib-2.63] lua/includes/util/color.lua:16: bad argument #1 to 'min' (number expected, got nil)
  1. min - [C]:-1
   2. hexToColor - lua/includes/util/color.lua:16
    3. func - addons/ulx-3.73/lua/ulx/xgui/settings/server.lua:1042
     4. callUpdate - addons/ulx-3.73/lua/ulx/modules/cl/xgui_client.lua:515
      5. fn - addons/ulx-3.73/lua/ulx/modules/cl/xgui_client.lua:467
       6. func - addons/ulib-2.63/lua/ulib/client/cl_util.lua:22
        7. unknown - lua/includes/extensions/net.lua:32

### Error(s) in player's console, if any
[ulib-2.63] lua/includes/util/color.lua:16: bad argument #1 to 'min' (number expected, got nil)
  1. min - [C]:-1
   2. hexToColor - lua/includes/util/color.lua:16
    3. func - addons/ulx-3.73/lua/ulx/xgui/settings/server.lua:1042
     4. callUpdate - addons/ulx-3.73/lua/ulx/modules/cl/xgui_client.lua:515
      5. fn - addons/ulx-3.73/lua/ulx/modules/cl/xgui_client.lua:467
       6. func - addons/ulib-2.63/lua/ulib/client/cl_util.lua:22
        7. unknown - lua/includes/extensions/net.lua:32

### Version
Run "ulx version" in console and paste the result
ULib v2.63
ULX v3.73

**Comment by zpetty33** [comment]
This seems like a misconfigured MOTD file. I am unable to replicate. If you are still having this issue, please open a new issue and attach your MOTD
