### ISSUE TITLE
ULib not allowing any right-click action (Context menu, Scoreboard, Spawn Menu, etc.)

### ISSUE THREAD

**Issue by stopher991** [TeamUlysses/ulib#69]
### Steps to reproduce
1. Spawn any prop
2. Try to use properties menu on prop
3. Receive errors from ULib

### Expected behavior
Tell us what should happen
All right click actions should be working as normal, and vgui panels should be appearing where users are right clicking, whether it be on props, scoreboard users, spawn menu items, or anything that will bring up a vgui panel.
### Actual behavior
Tell us what happens instead
An error (pasted below) occurs and a broken vgui panel with a single action (eg. "Keep Upright") appears on the top-left corner of the screen. These actions are not usable but are just ghost panels that will not go away, and cannot be replaced by opening another menu, except by disconnecting.

### Error(s) in server console, if any
[ulib] lua/includes/modules/properties.lua:63: attempt to index local 'option' (a nil value)
  1. AddOption - lua/includes/modules/properties.lua:63
   2. OpenEntityMenu - lua/includes/modules/properties.lua:83
    3. OnScreenClick - lua/includes/modules/properties.lua:98
     4. fn - lua/includes/modules/properties.lua:202
      5. Run - addons/ulib/lua/ulib/shared/hook.lua:109
       6. unknown - gamemodes/sandbox/gamemode/spawnmenu/contextmenu.lua:156

### Error(s) in player's console, if any
Same as above

### Version
Run "ulx version" in console and paste the result

ULib v2.63
ULX v3.73

**Comment by Nayruden** [comment]
Thanks for your interest in Ulysses projects!

Unfortunately, this error is not related to ULib. ULib is in the stack trace because we change the functionality of the gmod hooks, but the error is from the hook target.
