### ISSUE TITLE
[v2.63w] Changing phys_timescale Produces a Strange Bug

### ISSUE THREAD

**Issue by Peekofwar** [TeamUlysses/ulib#73]
### Steps to reproduce
1. Open the server settings in the admin section of the Utilities tab.
2. Click and drag the slider.
3. Release the slider and watch. Repeat step 2 a few times if nothing unusual happens.

### Expected behavior
The slider should stay where it was set to by the user.

### Actual behavior
The slider constantly moves between multiple values, which can be observed by watching the slider, or by querying the value in the console.

https://user-images.githubusercontent.com/10189526/115082932-87d6b400-9ebb-11eb-9d72-a870a0e72409.mp4

### Error(s) in server console, if any
N/A

### Error(s) in player's console, if any
N/A

### Version
ULib v2.63w
ULX v3.73w

**Comment by zpetty33** [comment]
I was able to replicate. This issue seems to be linked to our replicated CVar system. I am going to see if SticklyMan can get to the bottom of this since it's an issue with XGUI.

**Comment by Peekofwar** [comment]
> I was able to replicate. This issue seems to be linked to our replicated CVar system. I am going to see if SticklyMan can get to the bottom of this since it's an issue with XGUI.

So, despite XGUI not being open, it's still setting cvars? Maybe add a condition to where it only modifies the cvars if XGUI is open...

**Comment by zpetty33** [comment]
The problem is that it's replicated, so all users with access would need to get the updated value. I think we can fix it, it was just one of those little things that we never knew was happening. It's on our list to look at when we've got time to deep dive.

**Comment by SticklyMan** [comment]
@zpetty33 @Peekofwar I was able to reproduce this, but only on a listen server, not a dedicated server. Did either of you observe this on a dedicated server?

@zpetty33 I think I've got a workaround if you'd like to code review or test it. I'm working on some other fixes and getting the settings up-to-date with the latest changes in gmod, so I'll have a [larger PR with all of that in place](https://github.com/TeamUlysses/ulx/compare/master...feature/settings-improvements) soon.

https://github.com/TeamUlysses/ulx/commit/1a4b55679e69f5bedcc05c10b76b9b5d53b5270b
https://github.com/TeamUlysses/ulx/commit/64f8ab14c96645eedb916eba085a979897f4d534

**Comment by Peekofwar** [comment]
> @zpetty33 @Peekofwar I was able to reproduce this, but only on a listen server, not a dedicated server. Did either of you observe this on a dedicated server?
> 
> @zpetty33 I think I've got a workaround if you'd like to code review or test it. I'm working on some other fixes and getting the settings up-to-date with the latest changes in gmod, so I'll have a [larger PR with all of that in place](https://github.com/TeamUlysses/ulx/compare/master...feature/settings-improvements) soon.
> 
> [TeamUlysses/ulx@1a4b556](https://github.com/TeamUlysses/ulx/commit/1a4b55679e69f5bedcc05c10b76b9b5d53b5270b) [TeamUlysses/ulx@64f8ab1](https://github.com/TeamUlysses/ulx/commit/64f8ab14c96645eedb916eba085a979897f4d534)

Honestly, I don't remember if this happens on a dedicated server. I'd have to connect to my server and check.
