### ISSUE TITLE
Ban reason steamid showing up weird

### ISSUE THREAD

**Issue by wrefgtzweve** [TeamUlysses/ulib#85]
### Steps to reproduce
1. Configure the {{STEAMID}} replacement in the ulib ban message
2. Ban yourself
3. See ban message

### Expected behavior
Expected result would be the "normal" steamid like `STEAM_0:5:55476604`

### Actual behavior
Shows `0555476604` instead.

### Reason
Currently the steamid is being gsubbed before it's being used, I'm not sure why this is being done.
https://github.com/TeamUlysses/ulib/blob/ba112668cc55cb4d194a2660c78efb1da0cb75a6/lua/ulib/server/bans.lua#L27

Example:
![image](https://user-images.githubusercontent.com/69946827/182995603-e6065031-319d-4016-8869-4eb4fde193f8.png)

**Comment by zpetty33** [comment]
Fixed: I removed the gsub on the STEAMID replacement. I also fixed another bug I found with how gsub seems to be handled by glua now. Closing issue.
