### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RealDuckteam** [TeamUlysses/ulib#90]
[ulib] addons/ulib/lua/ulib/server/ucl.lua:1115: attempt to call upvalue 'playerAuth' (a nil value)
  1. fn - addons/ulib/lua/ulib/server/ucl.lua:1115
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:109
    3. UniqueID - [C]:-1
     4. echoToAdmins - addons/ulx/lua/ulx/log.lua:164
      5. fn - addons/ulx/lua/ulx/log.lua:202
       6. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

**Comment by iViscosity** [comment]
You're going to have to give a lot more context.

**Comment by SticklyMan** [comment]
Closing due to no response. Feel free to reply back if you're continuing to experience issues.
