### ISSUE TITLE
Entity a number

### ISSUE THREAD

**Issue by Zulbem** [TeamUlysses/ulib#93]
Got a bit of a problem which I don't know what causes it. Like once every 2 weeks, after a random map change, as the server loads, in the related functions mentioned in the errors below, what is meant to be an entity is somehow a number. The reason I've posted this here is the very first error that appears in console is by ulib, whether that's to do with ulib, I don't know really, but eventually, it'll just say lua panic attack and server crashes. Pretty sure this started since I updated ulib to latest but I'm not 100% sure. Thoughts?

```
[ulib] addons/ulib/lua/ulib/server/entity_ext.lua:164: attempt to index local 'ent' (a number value)
  1. fn - addons/ulib/lua/ulib/server/entity_ext.lua:164
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:109
    3. CleanUpMap - [C]:-1
```

```
[ulib] lua/includes/extensions/entity.lua:31: attempt to index local 'tab' (a number value)
  1. __index - lua/includes/extensions/entity.lua:31
   2. fn - addons/ulib/lua/ulib/server/entity_ext.lua:164
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:109
     4. CleanUpMap - [C]:-1
```

```
[ERROR] attempt to index a number value
  1. CleanUpMap - [C]:-1
```

**Comment by storm37000** [comment]
You are possibly running out of ram (it would say not enough memory with the lua panic) or your stack is either getting corrupted by a corrupt server file or an outdated/bad DLL module (/lua/bin).  Those are the only 2 things ive ever seen be able to cause a lua panic.

**Comment by Zulbem** [comment]
Correct. Corrupt addon. Resolved
